### ISSUE TITLE
OOM crash

### ISSUE THREAD

**Issue by SohumB** [matrix-hacks/matrix-puppet-hangouts#2] opened 2017-02-19 00:27 UTC
Hey, it's me again! Ran into a weird log/crash just now —

```
Feb 18 19:11:58 tars npm[15995]: ::ffff:127.0.0.1 - - [19/Feb/2017:00:11:58 +0000] "PUT /transactions/89?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/0.19.1"
Feb 18 19:11:58 tars npm[15995]: Sun, 19 Feb 2017 00:11:58 GMT matrix-puppet:Base:handleMatrixEvent:info incoming message. data: { age: 22,
Feb 18 19:11:58 tars npm[15995]: content: { body: 'what even, stanford', msgtype: 'm.text' },
Feb 18 19:11:58 tars npm[15995]: event_id: '<REDACTED>:nsb0.net',
Feb 18 19:11:58 tars npm[15995]: origin_server_ts: 1487463118872,
Feb 18 19:11:58 tars npm[15995]: room_id: '<REDACTED>',
Feb 18 19:11:58 tars npm[15995]: sender: '@sohum:nsb0.net',
Feb 18 19:11:58 tars npm[15995]: type: 'm.room.message',
Feb 18 19:11:58 tars npm[15995]: unsigned: { age: 22 },
Feb 18 19:11:58 tars npm[15995]: user_id: '@sohum:nsb0.net' }
Feb 18 19:11:58 tars npm[15995]: Sun, 19 Feb 2017 00:11:58 GMT matrix-puppet:Base:getThirdPartyRoomIdFromMatrixRoomId:info reducing array of alases to a 3prid
Feb 18 19:11:58 tars npm[15995]: Sun, 19 Feb 2017 00:11:58 GMT verbose:matrix-puppet:hangouts:client sending message to hangouts subprocess:  {"cmd":"sendmessage","conversation_id":"<REDACTED>","msgbody":"what even, stanford ​"}
Feb 18 19:11:59 tars npm[15995]: <--- Last few GCs --->
Feb 18 19:11:59 tars npm[15995]: [16006:0x2e17df0] 21317178 ms: Scavenge 1282.8 (1426.0) -> 1282.0 (1426.0) MB, 39.1 / 0.0 ms  (+ 53.1 ms in 384 steps since last GC) allocation failure
Feb 18 19:11:59 tars npm[15995]: [16006:0x2e17df0] 21319327 ms: Scavenge 1283.2 (1427.0) -> 1282.5 (1427.0) MB, 39.0 / 0.0 ms  (+ 1.7 ms in 399 steps since last GC) allocation failure
Feb 18 19:11:59 tars npm[15995]: [16006:0x2e17df0] 21319397 ms: Scavenge 1283.7 (1427.0) -> 1283.0 (1427.0) MB, 39.7 / 0.0 ms  (+ 2.0 ms in 414 steps since last GC) allocation failure
Feb 18 19:11:59 tars npm[15995]: <--- JS stacktrace --->
Feb 18 19:11:59 tars npm[15995]: Cannot get stack trace in GC.
Feb 18 19:11:59 tars npm[15995]: FATAL ERROR: Scavenger: promoting marked
Feb 18 19:11:59 tars npm[15995]: Allocation failed - process out of memory
Feb 18 19:11:59 tars npm[15995]: 1: node::Abort() [node]
Feb 18 19:11:59 tars npm[15995]: 2: 0x12dd38c [node]
Feb 18 19:11:59 tars npm[15995]: 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
Feb 18 19:11:59 tars npm[15995]: 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
Feb 18 19:11:59 tars npm[15995]: 5: 0x9e97ab [node]
Feb 18 19:11:59 tars npm[15995]: 6: void v8::internal::ScavengingVisitor<(v8::internal::MarksHandling)0, (v8::internal::PromotionMode)0, (v8::internal::LoggingAndProfiling)1>::EvacuateObject<(v8::internal::ScavengingVisitor<(v8::internal::MarksHandling)0, (v8::internal::PromotionMode)0, (v8::internal::LoggingAndProfiling)1>::ObjectContents)1, (v8::internal::AllocationAlignment)0>(v8::internal::Map*, v8::internal::HeapObject**, v8::internal::HeapObject*, int) [node]
Feb 18 19:11:59 tars npm[15995]: 7: v8::internal::Heap::IteratePromotedObjectPointers(v8::internal::HeapObject*, unsigned char*, unsigned char*, bool, void (*)(v8::internal::HeapObject**, v8::internal::HeapObject*)) [node]
Feb 18 19:11:59 tars npm[15995]: 8: void v8::internal::BodyDescriptorBase::IterateBodyImpl<v8::internal::ObjectVisitor>(v8::internal::HeapObject*, int, int, v8::internal::ObjectVisitor*) [node]
Feb 18 19:11:59 tars npm[15995]: 9: void v8::internal::BodyDescriptorApply<v8::internal::CallIterateBody, void, v8::internal::HeapObject*, int, v8::internal::ObjectVisitor*>(v8::internal::InstanceType, v8::internal::HeapObject*, int, v8::internal::ObjectVisitor*) [node]
Feb 18 19:11:59 tars npm[15995]: 10: v8::internal::Heap::DoScavenge(v8::internal::ObjectVisitor*, unsigned char*, v8::internal::PromotionMode) [node]
Feb 18 19:11:59 tars npm[15995]: 11: v8::internal::Heap::Scavenge() [node]
Feb 18 19:11:59 tars npm[15995]: 12: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
Feb 18 19:11:59 tars npm[15995]: 13: v8::internal::Heap::CollectGarbage(v8::internal::GarbageCollector, char const*, char const*, v8::GCCallbackFlags) [node]
Feb 18 19:11:59 tars npm[15995]: 14: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [node]
Feb 18 19:11:59 tars npm[15995]: 15: 0xf6b0b5 [node]
Feb 18 19:11:59 tars npm[15995]: 16: v8::internal::Map::EnsureDescriptorSlack(v8::internal::Handle<v8::internal::Map>, int) [node]
Feb 18 19:11:59 tars npm[15995]: 17: v8::internal::Map::ShareDescriptor(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Descriptor*) [node]
Feb 18 19:11:59 tars npm[15995]: 18: v8::internal::Map::CopyAddDescriptor(v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [node]
Feb 18 19:11:59 tars npm[15995]: 19: v8::internal::Map::CopyWithField(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::Representation, v8::internal::TransitionFlag) [node]
Feb 18 19:11:59 tars npm[15995]: 20: v8::internal::Map::TransitionToDataProperty(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [node]
Feb 18 19:11:59 tars npm[15995]: 21: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [node]
Feb 18 19:11:59 tars npm[15995]: 22: v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [node]
Feb 18 19:11:59 tars npm[15995]: 23: v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [node]
Feb 18 19:11:59 tars npm[15995]: 24: v8::internal::StoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [node]
Feb 18 19:11:59 tars npm[15995]: 25: v8::internal::Runtime_StoreIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [node]
Feb 18 19:11:59 tars npm[15995]: 26: 0x3d17fd2063a7
Feb 18 19:11:59 tars npm[15995]: Aborted
Feb 18 19:11:59 tars npm[15995]: ERROR:asyncio:Task exception was never retrieved
Feb 18 19:11:59 tars npm[15995]: future: <Task finished coro=<wrapper() done, defined at /usr/local/lib/python3.4/dist-packages/aiohttp/streams.py:396> exception=ServerDisconnectedError()>
Feb 18 19:11:59 tars npm[15995]: Traceback (most recent call last):
Feb 18 19:11:59 tars npm[15995]: File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
Feb 18 19:11:59 tars npm[15995]: result = coro.throw(exc)
Feb 18 19:11:59 tars npm[15995]: File "/usr/local/lib/python3.4/dist-packages/aiohttp/streams.py", line 398, in wrapper
Feb 18 19:11:59 tars npm[15995]: result = yield from func(self, *args, **kw)
Feb 18 19:11:59 tars npm[15995]: File "/usr/local/lib/python3.4/dist-packages/aiohttp/streams.py", line 454, in read
Feb 18 19:11:59 tars npm[15995]: return (yield from super().read(n))
Feb 18 19:11:59 tars npm[15995]: File "/usr/local/lib/python3.4/dist-packages/aiohttp/streams.py", line 187, in read
Feb 18 19:11:59 tars npm[15995]: yield from self._waiter
Feb 18 19:11:59 tars npm[15995]: File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
Feb 18 19:11:59 tars npm[15995]: yield self  # This tells Task to wait for completion.
Feb 18 19:11:59 tars npm[15995]: File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
Feb 18 19:11:59 tars npm[15995]: value = future.result()
Feb 18 19:11:59 tars npm[15995]: File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
Feb 18 19:11:59 tars npm[15995]: raise self._exception
Feb 18 19:11:59 tars npm[15995]: aiohttp.errors.ServerDisconnectedError
Feb 18 19:11:59 tars npm[15995]: Traceback (most recent call last):
Feb 18 19:11:59 tars npm[15995]: File "hangups_client.py", line 210, in listen_events
Feb 18 19:11:59 tars npm[15995]: msgJson = json.loads(msgtxt)
Feb 18 19:11:59 tars npm[15995]: File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
Feb 18 19:11:59 tars npm[15995]: return _default_decoder.decode(s)
Feb 18 19:11:59 tars npm[15995]: File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
Feb 18 19:11:59 tars npm[15995]: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Feb 18 19:11:59 tars npm[15995]: File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
Feb 18 19:11:59 tars npm[15995]: raise ValueError(errmsg("Expecting value", s, err.value)) from None
Feb 18 19:11:59 tars npm[15995]: ValueError: Expecting value: line 1 column 1 (char 0)
Feb 18 19:11:59 tars npm[15995]: During handling of the above exception, another exception occurred:
Feb 18 19:11:59 tars npm[15995]: Traceback (most recent call last):
Feb 18 19:11:59 tars npm[15995]: File "hangups_client.py", line 226, in <module>
Feb 18 19:11:59 tars npm[15995]: run_example(listen_events)
Feb 18 19:11:59 tars npm[15995]: File "hangups_client.py", line 69, in run_example
Feb 18 19:11:59 tars npm[15995]: loop.run_until_complete(task)
Feb 18 19:11:59 tars npm[15995]: File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
Feb 18 19:11:59 tars npm[15995]: return future.result()
Feb 18 19:11:59 tars npm[15995]: File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
Feb 18 19:11:59 tars npm[15995]: raise self._exception
Feb 18 19:11:59 tars npm[15995]: File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
Feb 18 19:11:59 tars npm[15995]: result = coro.throw(exc)
Feb 18 19:11:59 tars npm[15995]: File "hangups_client.py", line 115, in _async_main
Feb 18 19:11:59 tars npm[15995]: yield from example_coroutine(client, args)
Feb 18 19:11:59 tars npm[15995]: File "hangups_client.py", line 223, in listen_events
Feb 18 19:11:59 tars npm[15995]: print(json.dumps({"status":"error", "exception":repr(error)}))
Feb 18 19:11:59 tars npm[15995]: BrokenPipeError: [Errno 32] Broken pipe
Feb 18 19:11:59 tars npm[15995]: npm ERR! Linux 2.6.32-042stab120.16
Feb 18 19:11:59 tars npm[15995]: npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
Feb 18 19:11:59 tars npm[15995]: npm ERR! node v7.5.0
Feb 18 19:11:59 tars npm[15995]: npm ERR! npm  v4.1.2
Feb 18 19:11:59 tars npm[15995]: npm ERR! code ELIFECYCLE
Feb 18 19:11:59 tars npm[15995]: npm ERR! matrix-puppet-hangouts@0.0.1 start: `DEBUG=*matrix-puppet:* node index.js`
Feb 18 19:11:59 tars npm[15995]: npm ERR! Exit status 134
Feb 18 19:11:59 tars npm[15995]: npm ERR!
Feb 18 19:11:59 tars npm[15995]: npm ERR! Failed at the matrix-puppet-hangouts@0.0.1 start script 'DEBUG=*matrix-puppet:* node index.js'.
Feb 18 19:11:59 tars npm[15995]: npm ERR! Make sure you have the latest version of node.js and npm installed.
Feb 18 19:11:59 tars npm[15995]: npm ERR! If you do, this is most likely a problem with the matrix-puppet-hangouts package,
Feb 18 19:11:59 tars npm[15995]: npm ERR! not with npm itself.
Feb 18 19:11:59 tars npm[15995]: npm ERR! Tell the author that this fails on your system:
Feb 18 19:11:59 tars npm[15995]: npm ERR!     DEBUG=*matrix-puppet:* node index.js
Feb 18 19:11:59 tars npm[15995]: npm ERR! You can get information on how to open an issue for this project with:
Feb 18 19:11:59 tars npm[15995]: npm ERR!     npm bugs matrix-puppet-hangouts
Feb 18 19:11:59 tars npm[15995]: npm ERR! Or if that isn't available, you can get their info via:
Feb 18 19:11:59 tars npm[15995]: npm ERR!     npm owner ls matrix-puppet-hangouts
Feb 18 19:11:59 tars npm[15995]: npm ERR! There is likely additional logging output above.
Feb 18 19:11:59 tars npm[15995]: npm ERR! Please include the following file with any support request:
Feb 18 19:11:59 tars npm[15995]: npm ERR!     /home/sohum/matrix-puppet-hangouts/npm-debug.log
```

The server definitely wasn't out of memory; something like 10+gb was free at the time. 

The error resulted in a crash, and when node restarted, it never mirrored the incoming message _after_ the one listed at the top of the log.

**Comment by AndrewJDR** [comment] 2017-02-19 07:11
Hmm ok. I do have some hunches. I made some updates - pull down the latest and run that for a while to see if it still happens again.

If it does happen again, we'll have some additional debug output so please include your logs again.

**Comment by SohumB** [comment] 2017-02-19 07:46
Pulled, will let you know!

**Comment by AndrewJDR** [comment] 2017-02-19 08:46
I made another push. This adds an important feature:
The bridge will now create a special room called "Hangouts Protocol" and it will send you status information about the bridge itself. So any errors from the hangups subprocess, etc should be logged in there. This is pretty important since, for example, hangups might fail to send a message and you'd have no other way of knowing unless you were constantly inspecting your log files.

To start using this, pull latest and be sure to run ```npm update``` afterward.

**Comment by SohumB** [comment] 2017-02-19 18:31
On it, seems to be working fine! 
![screenshot from 2017-02-19 10-22-27](https://cloud.githubusercontent.com/assets/66472/23105049/bb498e50-f68d-11e6-8e57-717a29f8d218.png)

The last crash in the logs is from before I applied the earlier patch, so I'll keep keeping an eye out.

**Comment by AndrewJDR** [comment] 2017-02-19 20:28
Cool, and I made some updates to everything this morning, so you may want to re-pull and run `npm update` again.

Btw, After updating you may notice that it will create a new 'Hangouts Protocol' room. This is not a bug -- I decided to change the scheme I was using for the room alias, so it caused a new one to be created. you can just delete the old room.

**Comment by SohumB** [comment] 2017-02-20 23:26
:+1: 

I haven't had any further crashes since, but I have had some what appear to be fairly normal errors being reported in the debug room:

```
ERROR:asyncio:Unclosed connection
client_connection: 
```

```
ERROR:asyncio:Unclosed response
client_response: 
```

```
WARNING:hangups.channel:Long-polling request failed: Request timed out
ERROR:asyncio:Unclosed response
client_response: 
```

```
ERROR:asyncio:Unclosed connection
client_connection: 
```

**Comment by AndrewJDR** [comment] 2017-02-21 10:58
Great to hear.
And yes, those are messages that I've noticed on my end too, and they do seem to be pretty normal -- hangups apparently recovers quickly from these error conditions by reconnecting itself.
Down the line, I may try to filter out these "normal" errors. But since this is a relatively new bridge, I think I prefer the additional feedback for the time being.

**Comment by AndrewJDR** [comment] 2017-02-21 10:59
I'm going to close this for now. Please reopen if you run into the OOM again.

**Closed as completed by AndrewJDR** 2017-02-21 10:59 UTC
